# Generated by Django 2.0.13 on 2019-12-07 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('json2model', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateRequest',
        ),
    ]
